[package]
name = "inori"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.27.0"
nucleo-matcher = "*"
itertools = "*"
bitflags = "*"
toml = "*"
phf = {version = "*", features = ["macros"]}

[dependencies.mpd]
path = "./rust-mpd"
